---

- block:
    - name: Install containerd.io
      ansible.builtin.package: 
        name: containerd.io
        state: present
        update_cache: yes 

    - name: Create containerd directory
      ansible.builtin.file: 
        name: /etc/containerd
        state: directory
    
    - name: Check if config.toml is updated
      ansible.builtin.lineinfile:
        path: /etc/containerd/config.toml
        regexp: '^#[grpc]'
        state: absent
      check_mode: yes
      changed_when: false
      register: containerd_config

    - name: Render containerd default config
      ansible.builtin.shell: containerd config default > /etc/containerd/config.toml
      when: containerd_config.found

    - name: enable SystemdCgroup for containerd
      ansible.builtin.replace:
        path: /etc/containerd/config.toml
        regexp: '^(\s*)SystemdCgroup(.*)$'
        replace: '\1SystemdCgroup = true'
      notify:
        - reload containerd
    
    - name: Update the [grpc] block in /etc/containerd/config.toml
      ansible.builtin.blockinfile:
        path: /etc/containerd/config.toml
        marker: "{mark}"
        block: |2
            address = "{{ cri_socket_paths[kubernetes_cri] }}"
            gid = 0
            max_recv_message_size = 16777216
            max_send_message_size = 16777216
            tcp_address = ""
            tcp_tls_ca = ""
            tcp_tls_cert = ""
            tcp_tls_key = ""
            uid = 0
        marker_begin: "[grpc]"
        marker_end: "[metrics]"
      notify:
        - reload containerd

    # container runtime is inconsistent with that used by kubeadm
    # Ref. https://github.com/kubernetes/kubeadm/issues/3146
    - name: Update sandbox_image in /etc/containerd/config.toml
      ansible.builtin.lineinfile:
        path: /etc/containerd/config.toml
        regexp: '^\s*sandbox_image\s*=.*'
        line: '    sandbox_image = "{{ kubernetes_pause_image }}"'
        
    - name: render crictl.yaml
      ansible.builtin.template:
        src: crictl.yaml.j2
        dest: /etc/crictl.yaml
    
    - name: start and enable containerd
      ansible.builtin.systemd:
        name: containerd
        state: started
        enabled: yes
        
  when: kubernetes_cri == 'containerd'

- name: Force all notified handlers to run now
  meta: flush_handlers