---

- ansible.builtin.set_fact:
    kubernetes_iface: "{{ hostvars[inventory_hostname]['ansible_' + item ]['device'] }}"
  when: 
    - ansible_interfaces | length > 2
    - kubernetes_vip_ip is defined
    - hostvars[inventory_hostname]['ansible_' + item ].ipv4 is defined 
    - hostvars[inventory_hostname]['ansible_' + item ]['ipv4']['address'] | ansible.utils.ipaddr( kubernetes_subnet )
  with_items: "{{ ansible_interfaces }}"

- ansible.builtin.set_fact:
    kubernetes_iface: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['interface'] }}"
  when: 
    - ansible_interfaces | length <= 2

- block:
    - name: Download kube-flannel.yml
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
        dest: /root/kube-flannel.yml

    - name: Set flannel iface
      ansible.builtin.lineinfile:
        path: /root/kube-flannel.yml
        insertafter: '^(\s*).*kube-subnet-mgr(.*)$'
        line: '        - --iface={{ kubernetes_iface }}'

    - name: Install flannel
      ansible.builtin.command: kubectl apply -f /root/kube-flannel.yml
  when: kubernetes_cni == 'flannel'