---

- block:
    - name: disable ufw
      ansible.builtin.systemd:
        name: ufw 
        state: stopped 
        enabled: no
      when: disable_firewall
  when: ansible_os_family == 'Debian'

- block:

    - name: Install python3-libselinux
      ansible.builtin.package:
        name: python3-libselinux
        state: present

    - name: Remove zram-generator-defaults
      ansible.builtin.dnf: 
        name: 
          - zram-generator-defaults
        state: absent

    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: disable firewalld
      ansible.builtin.systemd:
        name: firewalld 
        state: stopped 
        enabled: no
      when: 
        - disable_firewall
        - "'firewalld' in ansible_facts.packages"

    - name: Put SELinux in permissive mode, logging actions that would be blocked.
      ansible.posix.selinux:
        policy: targeted
        state: permissive
      when: 
        - disable_selinux

    - name: Disable SELinux
      ansible.posix.selinux:
        state: disabled
      when: 
        - disable_selinux
  when: ansible_os_family == 'RedHat'

- name: Install containernetworking-plugins
  ansible.builtin.package:
    name: containernetworking-plugins
    state: present
  when: 
    - ansible_distribution == 'Fedora'

- name: Install openssl
  ansible.builtin.package: 
    name: 
      - openssl
    state: present

- name: load overlay kernel module
  ansible.builtin.command: modprobe overlay

- name: load br_netfilter kernel module
  ansible.builtin.command: modprobe br_netfilter

- name: load kernel modules - persistent
  blockinfile:
    path: /etc/modules-load.d/containerd.conf
    create: yes
    block: |
      overlay
      br_netfilter

- name: Modify sysctl parameters - persistent
  blockinfile:
    path: /etc/sysctl.d/99-kubernetes-cri.conf
    create: yes
    block: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.ipv4.ip_forward                 = 1
      net.bridge.bridge-nf-call-ip6tables = 1

- name: load br_netfilter kernel module
  ansible.builtin.command: sysctl --system

- name: Disable SWAP
  ansible.builtin.shell: |
    swapoff -a

- name: Disable SWAP in fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^(\s*)([^#\n]+\s+)(\w+\s+)swap(\s+.*)$'
    replace: '#\1\2\3swap\4'
    backup: yes

- block:
    - name: Install open-iscsi,nfs-common using apt
      ansible.builtin.apt: 
        name: 
          - open-iscsi
          - nfs-common
        state: present 

    - name: start and enable iscsid
      ansible.builtin.systemd:
        name: iscsid
        state: started
        enabled: yes
  when:
    - install_longhorn
    - inventory_hostname in groups['kubeworker']