---

- name: Install required system packages
  ansible.builtin.apt: 
    name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
    update_cache: yes 
    force_apt_get: yes

- name: Create /etc/apt/keyrings/ directory
  ansible.builtin.file:
    path: /etc/apt/keyrings/
    state: directory
    mode: '0755'

- name: Add K8s Repository key
  ansible.builtin.get_url:
    url:  https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_major }}/deb/Release.key
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.key

- name: Add K8s Repository
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/kubernetes.list
    regexp: '^deb'
    line: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.key] https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_major }}/deb/ /
    create: yes

- name: Add Docker Repository key
  ansible.builtin.get_url:
    url:  https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc

- shell: . /etc/os-release && echo "$VERSION_CODENAME"
  register: lsb_release

- shell: dpkg --print-architecture
  register: deb_architecture

- name: Add Docker Repository
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/docker.list
    regexp: '^deb'
    line: deb [arch={{ deb_architecture.stdout }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ lsb_release.stdout }} stable
    create: yes