---

# kubevip needs super-admin.conf privileges
# Ref. https://github.com/kube-vip/kube-vip/issues/684
- ansible.builtin.set_fact:
    kube_vip_permission: "{% if kubernetes_init_host is defined and  kubernetes_init_host == inventory_hostname %}super-admin.conf{% else %}admin.conf{% endif %}"

- name: Create /etc/kubernetes/manifests/ directory
  ansible.builtin.file: 
    name: /etc/kubernetes/manifests/
    state: directory

- name: render kube-vip.yml
  ansible.builtin.template:
    src: kube-vip.yml.j2
    dest: /etc/kubernetes/manifests/kube-vip.yaml
  notify:
    - wait kube-vip